version: '3'

services:
    forms-response-datastore:
      image: mongo:3.0.2
      networks:
          - forms-response
    forms-response-service:      
      build: .
      command: python -u main.py
      ports:
        - "5000:8080"
      networks:
          - forms-response
networks:
    forms-response:

